Switched off listeners limit for tests
dial-once/node-bunnymq pull request #62
Opened 2016-12-23 11:20 UTC by Spring3

resolves #40 
I wanted to ask if I need to increase the limit during the normal run of this module?
Currently I disabled listeners limit for tests

2016-12-23 11:58 UTC, mrister approved these changes

2016-12-23 11:59 UTC, mrister commented
@Spring3 I think we should leave the limit and let the user of the lib to set the up how he/she sees/fit. Maybe we should do that with an env var or something to be easier to set up.

2016-12-26 08:17 UTC, ykhatal approved these changes

2016-12-26 08:31 UTC, jkernech requested changes
I think you should put a default value as fallback, if the env var is not defined.

2016-12-26 08:31 UTC, jkernech commented on src/index.js
> +process.set
What is the purpose of this line ?

2017-01-09 09:38 UTC, jkernech approved these changes

2017-01-09 09:52 UTC, merged