Prioritized config value over env vars.
dial-once/node-bunnymq pull request #64
Opened 2017-01-02 12:33 UTC by Spring3

Resolves #63 

Reviewers: @jkernech @ky23 @mrister

2017-01-02 15:34 UTC, mrister approved these changes

2017-01-06 09:46 UTC, ykhatal requested changes
well done, but i think you've missed some var like the prefetch count, the debug ..

2017-01-06 10:22 UTC, Spring3 commented
@ky23 I think they are not overwritten by env vars. They are just being taken from config or fall back to default value if config does not have one.

2017-01-09 09:37 UTC, jkernech approved these changes

2017-01-09 10:49 UTC, ykhatal approved these changes
@Spring3  thanks for the update

2017-01-11 12:07 UTC, merged