Feature/rework exposed methods
dial-once/node-bunnymq pull request #75
Opened 2017-02-09 12:50 UTC by Spring3

#61 Was based on `refactor/es6`, so I created this one to merge into `develop`

2017-02-09 13:32 UTC, mrister requested changes
Nice work just a few suggestions/questions

2017-02-09 13:32 UTC, mrister commented on src/index.js
> +  const hostnameFallback = uuid.v4();
since hostnameFallback var is not used no need to declare it, just use uuid.v4();

2017-02-09 13:32 UTC, mrister commented on src/modules/bunnymq.js
> +class Consumer {
maybe it would be good to separate to each class to it's own file, what do you think?

2017-02-09 13:32 UTC, mrister commented on src/modules/bunnymq.js
> +   /* eslint no-param-reassign: "off" */
is this still needed, will eslint throw this error even though you are just passing it to another function?

2017-02-09 13:32 UTC, mrister commented on src/modules/bunnymq.js
> +module.exports = (connection) => {
would it make more sense to export a default instance that is also configured like this but also allow users to create instances as they see fit? maybe export the classes also. Just food for thought

2017-02-09 13:32 UTC, mrister commented on src/modules/retrocompat-config.js
> -  if (process.env.LOCAL_QUEUE && !config.consumerSuffix) {
why remove the `&& !config.consumerSuffix`?

2017-02-09 13:32 UTC, mrister commented
oh and squash please.

2017-02-09 13:36 UTC, Spring3 commented on src/modules/bunnymq.js
> +class Consumer {
It was in different files before squash.... will fix this

2017-02-09 14:29 UTC, Spring3 commented on src/modules/bunnymq.js
> +module.exports = (connection) => {
After you create an instance of BunnyMQ, all "private" fields are exposed automatically. So, you have acces to either consumer or producer. JS's "private" properties are actually not private at all :)

2017-02-09 14:58 UTC, mrister commented
ou some confilcs need to be resolved.

2017-02-16 08:54 UTC, mrister requested changes
It's good just some comments, squash and updating branch to not have conflicts.

2017-02-28 13:58 UTC, Spring3 commented
@mrister I will resolve conflicts, but it will break down the tests on this PR because ``docker`` here has a ``start`` and ``stop`` functions, but on the ``develop`` branch, ``start`` and ``rm``

2017-02-28 14:33 UTC, mrister commented
@Spring3 Commands ned to be adjusted per develop.

2017-02-28 16:37 UTC, Spring3 commented
@mrister squashed and merged, but as expected, tests are now broken at the place where docker is called

2017-03-10 13:51 UTC, dialonce commented on src/modules/producer.js
>    set connection(value) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Provide a getter matching this setter for 'connection'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.dialonce.io/coding_rules#rule_key=javascript%3AS2376)

2017-03-10 13:51 UTC, dialonce commented on src/modules/consumer.js
>    set connection(value) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Provide a getter matching this setter for 'connection'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.dialonce.io/coding_rules#rule_key=javascript%3AS2376)

2017-03-10 13:51 UTC, dialonce commented
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 2 major

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

2017-03-10 14:21 UTC, mrister commented
@Spring3 Can you check when you get time what is causing the docker problems in tests.

2017-03-13 11:39 UTC, Spring3 commented
@dial-once/developers Tests are failing due to a [lack of write rights](https://circleci.com/docs/1.0/docker-btrfs-error/) for the storage where this app is being deployed by ``CircleCI``. So, I think we need to consider using the old ``stop`` command instead of ``rm`` as added in #76

2017-03-13 13:20 UTC, mrister commented on src/modules/consumer.js
>    set connection(value) {
I guess this rule dos not make much sense when it is by design

2017-03-13 13:23 UTC, mrister approved these changes
Nice Fix @Spring3 !

2017-03-14 11:42 UTC, Spring3 commented
@mrister Switched the approach to slightly modifying the rm function to
``docker rm -f rabbitmq-bunnymq || true`` as suggested [here](https://discuss.circleci.com/t/docker-error-removing-intermediate-container/70)

2017-03-14 13:33 UTC, mrister commented
@spring3 tnx for the update.

2017-03-14 14:03 UTC, jkernech approved these changes
👍

2017-03-15 09:36 UTC, Spring3 commented
@ky23 bump

2017-03-15 19:26 UTC, ykhatal approved these changes

2017-03-16 14:11 UTC, merged