Fix requeuing issue when buffer is full
dial-once/node-bunnymq pull request #87
Opened 2017-05-23 14:06 UTC by ky23

This is a fix for when the function `publishOrSendToQueue` return false which means that the buffer is full.
But after testing it, i noticed that even if the function return false, the message still get published to the broker. So for the fix i removed this logic to avoid message duplication.

2017-05-23 14:10 UTC, Spring3 commented on src/modules/bunnymq.js
> +      publish: instance.publish.bind(instance)
👍  🥇  Thanks :)

2017-05-23 14:24 UTC, Spring3 commented on src/index.js
> +    rpcTimeout: 15000,
isn't 15 seconds too much?

2017-05-23 14:28 UTC, Spring3 commented on src/modules/bunnymq.js
> +      publish: instance.publish.bind(instance)
The only thing is that we need to keep ``procuder`` and ``consumer`` for ``produce`` and ``consume`` functions only (just to keep the backwards compat). ``subscribe`` and ``publish`` should be exposed out of the object as requested [here](https://github.com/dial-once/node-bunnymq/issues/41) @dial-once/developers Do you think we need to do it? Or keep it as Yacine has it right now?

2017-05-23 14:32 UTC, Spring3 requested changes
Fix tests

2017-05-23 14:49 UTC, mrister commented on src/index.js
> +    rpcTimeout: 15000,
I think the idea is to override it in projects but give generous time per default.

2017-05-23 14:56 UTC, mrister requested changes
We need to support both the output object (backward compatibility) and the newly exported functions

2017-05-23 14:56 UTC, mrister commented on src/modules/bunnymq.js
> +      publish: instance.publish.bind(instance)
I think we need to support both for backward compatibility and to satisfy the need by the issue you mentioned, @ky23 ?

2017-05-23 15:51 UTC, mrister approved these changes

2017-05-24 08:27 UTC, jkernech approved these changes

2017-05-24 08:40 UTC, williamluang approved these changes

2017-05-24 08:42 UTC, Spring3 approved these changes

2017-05-24 09:09 UTC, ofkindness commented on src/modules/bunnymq.js
> +    consumer,
```
consumer , 
producer
``` 
- since they in shorthand notation better put on top of returning object definition

2017-05-24 09:50 UTC, merged