Fixture/update config files
dial-once/node-bunnymq pull request #96
Opened 2018-08-19 11:32 UTC by steven-heng

Npm audit found 0 vulnerabilities
Modify Dockerfile and test built successfully
Modify rules command of package.json and Makefile
Add badges in README.md
Update package-lock.json

2018-08-20 14:31 UTC, jkernech requested changes

2018-08-20 14:31 UTC, jkernech commented on Makefile
>  	sed -i 's/{service-name}/$(NAME)/g' README.md
You can remove those 3 lines, they are only used to init the project once

2018-08-20 14:31 UTC, jkernech commented on Makefile
> +	@sonar-scanner-2.8/bin/sonar-runner -e -Dsonar.analysis.mode=publish -Dsonar.host.url=$(SONAR_HOST_URL) -Dsonar.login=$(SONAR_LOGIN) -Dsonar.password=$(SONAR_PASS)
You can use `sonar-scanner` here, `sonar-runner` is deprecated

2018-08-24 08:02 UTC, mrister approved these changes

2018-09-03 08:19 UTC, jkernech approved these changes

2018-09-03 08:19 UTC, merged